services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=false
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data       # Persistencia unificada
      - ./nifi_state:/opt/nifi/nifi-current/state     # Estado del servicio
      - ./nifi_logs:/opt/nifi/nifi-current/logs 
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - nifi_net

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ./zookeeper_data:/data
      - ./zookeeper_datalog:/datalog
    restart: unless-stopped
    networks:
      - nifi_net

volumes:
  nifi_data:
  nifi_state:
  zookeeper_data:
  zookeeper_datalog:

networks:
  nifi_net:
    driver: bridge
